### ISSUE TITLE
use '---' as slides separator

### ISSUE THREAD

**Issue by setop** [wanadev/wanaprez#2]
[Marp](https://marpit.marp.app/markdown?id=how-to-write-slides) and [Revealjs](https://revealjs.com/markdown/) have chosen "---" ad slides separator and I think it is a good choice.
Maybe wanaprez should do the same instead of "###", the third level of titles.

**Comment by flozz** [comment]
Hello,

Thank you for your suggestion :)

For Wanaprez we made the choice to use titles as separator; it help to have a better plan and to avoid useless slides. Of course not everyone will like it, but that's why there is choices (like Marp and Revealjs you mentioned). ;)

Have a nice day :)

**Comment by setop** [comment]
Hi @flozz,

Thanks for the reply.
I understand your choice, especially for quick building of presentation, it is relevant.
The longer I played with it, the more I get convinced.

Cheers
